### ISSUE TITLE
cma-ssh crash during sbrain deployment in Santa Clara

### ISSUE THREAD

**Issue by notjames** [samsung-cnct/cma-ssh#141]
cma-ssh crash(es) captured on cacpu02 in /var/tmp/cma-ssh-crashes.out

```
I0611 15:18:24.977210       1 request.go:942] Response Body: {"kind":"Event","apiVersion":"v1","metadata":{"name":"worker-gpu.15a72df009d600a1","namespace":"sbrain-customer","selfLink":"/api/v1/namespaces/sbrain-customer/events/worker-gpu.15a72df009d600a1","uid":"2815b062-8c5c-11e9-ab08-2c600c836c9b","resourceVersion":"1103697","creationTimestamp":"2019-06-11T15:18:24Z"},"involvedObject":{"kind":"CnctMachineSet","namespace":"sbrain-customer","name":"worker-gpu","uid":"fbb8bfed-8c55-11e9-ab08-2c600c836c9b","apiVersion":"cluster.cnct.sds.samsung.com/v1alpha1","resourceVersion":"1103690"},"reason":"ResourceStateChange","message":"Resource \"worker-gpu\" changed state to \"ReadyMachineSet\"","source":{"component":"MachineSetController"},"firstTimestamp":"2019-06-11T15:18:24Z","lastTimestamp":"2019-06-11T15:18:24Z","count":2,"type":"Normal","eventTime":null,"reportingComponent":"","reportingInstance":""}
E0611 15:18:27.738886       1 client.go:110] Create failed to deploy machine sbrain-customer-worker-gpu-2fc87: unexpected: ServerError: 400 Bad Request ({"storage": ["Mount the root '/' filesystem to be able to deploy this node."]})
E0611 15:18:27.839959       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76                                                                                  
/go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65                                                                                  
/go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51                                                                                  
/usr/local/go/src/runtime/panic.go:522
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/github.com/samsung-cnct/cma-ssh/pkg/controller/machine/create.go:432
/go/src/github.com/samsung-cnct/cma-ssh/pkg/controller/machine/create.go:110
/go/src/github.com/samsung-cnct/cma-ssh/pkg/controller/machine/machine_controller.go:210
/go/src/github.com/samsung-cnct/cma-ssh/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215                                                            
/go/src/github.com/samsung-cnct/cma-ssh/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158                                                            
/go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133                                                                                       
/go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134                                                                                       
/go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88                                                                                        
/usr/local/go/src/runtime/asm_amd64.s:1337
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1315a84]

goroutine 308 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105                                                                   
panic(0x147a3a0, 0x254f260)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/samsung-cnct/cma-ssh/pkg/controller/machine.(*creator).doMaasCreate(0xc00064ca80)                                                                                       
        /go/src/github.com/samsung-cnct/cma-ssh/pkg/controller/machine/create.go:436 +0xf4
github.com/samsung-cnct/cma-ssh/pkg/controller/machine.create(0x19247c0, 0xc0006c8080, 0xc0006c80a8, 0xc0003b5500, 0x0, 0x0)                                                       
        /go/src/github.com/samsung-cnct/cma-ssh/pkg/controller/machine/create.go:110 +0x1ee                                                                                        
github.com/samsung-cnct/cma-ssh/pkg/controller/machine.(*ReconcileMachine).Reconcile(0xc0006c8080, 0xc0004c2d80, 0xf, 0xc0004c2d60, 0x10, 0x2568c40, 0xc0004505d8, 0x40bf98, 0x20)
        /go/src/github.com/samsung-cnct/cma-ssh/pkg/controller/machine/machine_controller.go:210 +0x13b9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0003f8140, 0x0)
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215 +0x1cc
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36                                              
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00088bc40)
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54                                                                         
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00088bc40, 0x3b9aca00, 0x0, 0x1, 0xc0002f96e0)                                                                                    
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xf8                                                                         
k8s.io/apimachinery/pkg/util/wait.Until(0xc00088bc40, 0x3b9aca00, 0xc0002f96e0)
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d                                                                          
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
        /go/src/github.com/samsung-cnct/cma-ssh/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x311```

**Comment by notjames** [comment]
Looking at that a little more (though I'm very tired so this may not be accurate) I decided to try and release the affected machine. Supposing that the machine's system_id was from
```
I0611 15:28:54.027934       1 request.go:942] Response Body: {"kind":"Event","apiVersion":"v1","metadata":{"name":"worker-gpu.15a72e82771ed287","namespace":"sbrain-dev","selfLink":
"/api/v1/namespaces/sbrain-dev/events/worker-gpu.15a72e82771ed287","uid":"9ef30a18-8c5d-11e9-ab08-2c600c836c9b","resourceVersion":"1104505","creationTimestamp":"2019-06-11T15:28:53
Z"},"involvedObject":{"kind":"CnctMachineSet","namespace":"sbrain-dev","name":"worker-gpu","uid":"a2aa868d-8c55-11e9-ab08-2c600c836c9b","apiVersion":"cluster.cnct.sds.samsung.com/v
1alpha1","resourceVersion":"1104490"},"reason":"ResourceStateChange","message":"Resource \"worker-gpu\" changed state to \"ReadyMachineSet\"","source":{"component":"MachineSetContr
oller"},"firstTimestamp":"2019-06-11T15:28:53Z","lastTimestamp":"2019-06-11T15:28:54Z","count":3,"type":"Normal","eventTime":null,"reportingComponent":"","reportingInstance":""}   
E0611 15:28:56.755845       1 client.go:110] Create failed to deploy machine sbrain-customer-worker-gpu-vbwgk: unexpected: ServerError: 400 Bad Request ({"storage": ["Mount the roo
t '/' filesystem to be able to deploy this node."]})                                                                                                                                
E0611 15:28:56.857209       1 runtime.go:69] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```
or `sbrain-customer-worker-gpu-vbwgk`. When I looked for this machine, I ended up getting:

```
sbrain@cacpu02:~/sbrain/clusters/cms-creation/customer$ jq -Mr '.[] | select(.system_id == "vbwgk") | .hostname' /var/tmp/machines.json                                            
sbrain@cacpu02:~/sbrain/clusters/cms-creation/customer$ jq -Mr '.[] | select(.system_id == "vbwgk")' /var/tmp/machines.json                                                        
sbrain@cacpu02:~/sbrain/clusters/cms-creation/customer$ grep vbwgk /var/tmp/machines.json

```
